"""Investor module -- MCP client interface to financial-mcp-server."""

from src.investor.mcp_client import (
    is_connected,
    score_ticker,
    scan_universe,
    analyze_ticker,
    get_fundamentals,
    get_momentum,
    get_price,
    create_portfolio,
    analyze_portfolio,
    get_holdings,
    get_trades,
    execute_buy,
    execute_sell,
    run_rebalance,
    check_risk,
    detect_market_regime,
    get_vix_analysis,
    scan_anomalies,
    scan_volume_leaders,
    scan_gap_movers,
    get_smart_money_signal,
    get_futures_positioning,
)

__all__ = [
    "is_connected",
    "score_ticker",
    "scan_universe",
    "analyze_ticker",
    "get_fundamentals",
    "get_momentum",
    "get_price",
    "create_portfolio",
    "analyze_portfolio",
    "get_holdings",
    "get_trades",
    "execute_buy",
    "execute_sell",
    "run_rebalance",
    "check_risk",
    "detect_market_regime",
    "get_vix_analysis",
    "scan_anomalies",
    "scan_volume_leaders",
    "scan_gap_movers",
    "get_smart_money_signal",
    "get_futures_positioning",
]
